
x-superset-image: &superset-image amancevice/superset:2.0.0
x-superset-depends-on: &superset-depends-on
  - db
  - redis
  - etl_app
x-superset-volumes: &superset-volumes
  - ./docker/docker-init.sh:/app/docker-init.sh
  - ./docker/euro-dashboard.json:/app/euro-dashboard.json
  - ./docker/PostgreExternals.yaml:/app/PostgreExternals.yaml
  - ./docker/pythonpath_dev:/app/pythonpath
  - superset_home:/app/superset_home


version: "3.7"

services:
  ofelia:
    image: mcuadros/ofelia:latest
    restart: always
    container_name: ofelia
    depends_on:
      - etl_app
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.enabled: "true"
      ofelia.job-run.app.schedule: "0 0 21 * * TUE,FRI" # * * 21 * 2
      ofelia.job-run.app.container: "etl-app"

  etl_app:
    image: etl-app
    container_name: etl_app
    #restart: always
    user: user
    env_file: docker/.env-prod
    command: [ "python", "./etl/etl_app.py", "etl" ]
    build:
      context: .
      dockerfile: etl/Dockerfile
    volumes:
      - ./etl:/etl-app
    depends_on:
      - "db"
      - "pgadmin"
  #  labels:
  #    ofelia.enabled: "true"
  #    ofelia.job-exec.etl-app.schedule: "@every 10s"
  #    ofelia.job-exec.etl-app.command: "pwd"

  db:
    image: postgres:10
    container_name: db
    env_file: docker/.env-prod
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf", "-c", "hba_file=/etc/postgresql/pg_hba.conf" ]
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - db_home:/var/lib/postgresql/data
      - ./docker/postgresqlconfig/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/postgresqlconfig/pg_hba.conf:/etc/postgresql/pg_hba.conf

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: docker/.env-prod
    ports:
      - '5050:80'
    restart: unless-stopped
    depends_on:
      - "db"
    volumes:
      - pgadmin:/root/.pgadmin

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - redis:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    restart: unless-stopped
    env_file: docker/.env-prod
    ports:
      - '8081:8081'
    depends_on:
      - redis

  superset:
    env_file: docker/.env-prod
    image: *superset-image
    container_name: superset_app
    command: [ "flask", "run", "-p", "8088", "--with-threads", "--reload", "--debugger", "--host=0.0.0.0" ]
    restart: unless-stopped
    ports:
      - "8088:8088"
    depends_on: *superset-depends-on
    volumes: *superset-volumes

  superset-init:
    env_file: docker/.env-prod
    image: *superset-image
    container_name: superset_init
    command: ["/app/docker-init.sh"]
    user: "root"
    depends_on: *superset-depends-on
    volumes: *superset-volumes

volumes:
  db_home:
    external: false
  pgadmin:
    external: false
  redis:
    external: false
  superset_home:
    external: false