
version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file: docker/.env-prod
        container_name: etl_app
        command: ["python", "./main.py", "app"]
        restart: always
        volumes:
            - ./:/app
        depends_on:
            - "db"
            - "redis"
            - "pgadmin"
    redis:
        image: redis:latest
        container_name: etl_redis
        restart: unless-stopped
        ports:
            - "127.0.0.1:6379:6379"
        volumes:
            - redis:/data
    db:
        image: postgres:10
        container_name: etl_db
        env_file: docker/.env-prod
        command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - database-data:/var/lib/postgresql/data/
            - ./docker/postgresqlconfig/postgresql.conf:/etc/postgresql/postgresql.conf
            - ./docker/postgresqlconfig/pg_hba.conf:/etc/postgresql/pg_hba.conf

    pgadmin:
        image: dpage/pgadmin4
        container_name: etl_pgadmin
        env_file: docker/.env-prod
        ports:
            - '5050:80'
        restart: always
        depends_on:
            -   "db"
        volumes:
            - pgadmin:/root/.pgadmin
volumes:
    database-data:
        external: false
    pgadmin:
        external: false
    redis:
        external: false